CREATE TABLE dim_asset(id VARCHAR, file_name VARCHAR, start_time INTEGER, stop_time INTEGER, created_by VARCHAR, created_on VARCHAR, modified_by VARCHAR, modified_on VARCHAR, description INTEGER, file_hash VARCHAR, note INTEGER, asset_group_id INTEGER, "type" VARCHAR, duration DOUBLE, file_size INTEGER, "extension" VARCHAR, process_id BIGINT, s3_key VARCHAR);;
CREATE TABLE dim_asset_fbf_object_link(asset_id VARCHAR, object_id BIGINT);;
CREATE TABLE dim_asset_frame_link(asset_id VARCHAR, frame_id BIGINT);;
CREATE TABLE dim_customer(id INTEGER, created_by VARCHAR, created_on VARCHAR, modified_by VARCHAR, modified_on VARCHAR, "name" VARCHAR, description INTEGER, code_name INTEGER);;
CREATE TABLE dim_frame(_source VARCHAR, process_name VARCHAR, frame_groupid VARCHAR, subprocess_name VARCHAR, task_name VARCHAR, "name" VARCHAR, derived_from_frame_id INTEGER, "type" VARCHAR, imported BOOLEAN, additional_note INTEGER, created_by VARCHAR, modified_by VARCHAR, _insertion_order BIGINT, project_id INTEGER, task_id BIGINT, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, subject VARCHAR, fbf_action VARCHAR, fbf_object VARCHAR, indirect_object VARCHAR, footage_timestamp FLOAT, start_time INTERVAL, "sequence" BIGINT, id BIGINT, stop_time INTERVAL);;
CREATE TABLE dim_frame_factory_frame(footage_timestamp FLOAT, customer VARCHAR, project VARCHAR, process VARCHAR, subprocess VARCHAR, task VARCHAR, frame VARCHAR, customer_key VARCHAR, project_key VARCHAR, process_key VARCHAR, subprocess_key VARCHAR, task_key VARCHAR);;
CREATE TABLE dim_frame_fbf_object_link(frame_id BIGINT, object_id BIGINT, "type" VARCHAR);;
CREATE TABLE dim_hazard(_source VARCHAR, "type" VARCHAR, created_by VARCHAR, modified_by VARCHAR, frame_id BIGINT, process_name VARCHAR, subprocess_name VARCHAR, task_name VARCHAR, frame VARCHAR, "name" VARCHAR, hazard_specification VARCHAR, hazard_object VARCHAR, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, parameter_map JSON, hazard_category VARCHAR, "sequence" BIGINT, id BIGINT, specification_id BIGINT, fbf_object_id BIGINT);;
CREATE TABLE dim_hazard_specification(_source VARCHAR, four_eye_principle INTEGER, sop_instructed INTEGER, label_verification INTEGER, nvp INTEGER, active_air INTEGER, passive_air INTEGER, batch_record_review INTEGER, created_by VARCHAR, modified_by VARCHAR, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, project_id INTEGER, "name" VARCHAR, id BIGINT);;
CREATE TABLE dim_object("name" VARCHAR, "type" VARCHAR, parameter_spec VARCHAR, critical_surfaces INTEGER, description INTEGER, object_group_id INTEGER, is_active INTEGER, start_time INTEGER, stop_time INTEGER, note INTEGER, count INTEGER, size VARCHAR, weight VARCHAR, handling_difficulty VARCHAR, decontamination VARCHAR, filter_integrity_testing VARCHAR, hepa_filter_integrity_testing VARCHAR, sterilization_in_place VARCHAR, sterilization VARCHAR, cleaning_in_place VARCHAR, cleaning_procedures VARCHAR, equipment_cleaning_procedures VARCHAR, material_personnel_flow VARCHAR, surface_disinfection VARCHAR, zoning_concept VARCHAR, double_bagging VARCHAR, redundant_equipment VARCHAR, single_use_systems VARCHAR, contact_surface_plates VARCHAR, swabs VARCHAR, created_by VARCHAR, modified_by VARCHAR, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, _source VARCHAR, process_name VARCHAR, derived_from_object_id BIGINT, process_id BIGINT, id BIGINT);;
CREATE TABLE dim_process(_source VARCHAR, "name" VARCHAR, derived_from_process_id INTEGER, process_category INTEGER, process_category_status INTEGER, "version" INTEGER, reconciliation INTEGER, visual_checks INTEGER, one_hundred_percent_vi INTEGER, container_closure_integrity_testing INTEGER, fill_volume_weight_check INTEGER, semi_automated_visual_inspection INTEGER, visual_stopper_inspection INTEGER, process_parameter_trending INTEGER, cleanroom_parameter_monitoring INTEGER, personnel_monitoring INTEGER, product_release_testing INTEGER, is_frozen BOOLEAN, created_by VARCHAR, modified_by VARCHAR, parameter_map JSON, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, project_id INTEGER, id BIGINT);;
CREATE TABLE dim_project(id INTEGER, created_by VARCHAR, created_on VARCHAR, modified_by VARCHAR, modified_on VARCHAR, project_status VARCHAR, "name" VARCHAR, site_id INTEGER, customer_id INTEGER, "type" VARCHAR, product_name VARCHAR, dosage_form INTEGER, target_concentration INTEGER, active_ingredient INTEGER, excipients INTEGER, sensitivity INTEGER, manufacturing_site VARCHAR, filling_line VARCHAR, target_volume INTEGER);;
CREATE TABLE dim_subprocess(_source VARCHAR, derived_from_subprocess_id INTEGER, parameter_map INTEGER, created_by VARCHAR, modified_by VARCHAR, process_name VARCHAR, "name" VARCHAR, process_id BIGINT, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, "sequence" BIGINT, id BIGINT);;
CREATE TABLE dim_task(_source VARCHAR, process_name VARCHAR, derived_from_task_id INTEGER, parameter_map INTEGER, created_by VARCHAR, modified_by VARCHAR, subprocess_id BIGINT, subprocess_name VARCHAR, "name" VARCHAR, created_on TIMESTAMP WITH TIME ZONE, modified_on TIMESTAMP WITH TIME ZONE, "sequence" BIGINT, id BIGINT);;
CREATE TABLE raw_object(ObjectID VARCHAR, "Unique Objects" VARCHAR, decontamination VARCHAR, "filter integrity testing" VARCHAR, "hepa filter integrity testing" VARCHAR, "sterilization in place" VARCHAR, sterilization VARCHAR, "cleaning in place" VARCHAR, "cleaning procedures" VARCHAR, "equipment cleaning procedures" VARCHAR, "material/personnel flow" VARCHAR, "surface disinfection" VARCHAR, "zoning concept" VARCHAR, "double-bagging" VARCHAR, "redundant equipment" VARCHAR, "single use systems" VARCHAR, "contact surface plates" VARCHAR, swabs VARCHAR, "object type" VARCHAR, WeightObj VARCHAR, SizeObj VARCHAR, HandlingOfObj VARCHAR, WeightObjScr VARCHAR, SizeObjScr VARCHAR, HandlingOfObjScr VARCHAR, ComplexityScr VARCHAR, _source VARCHAR);;
CREATE TABLE raw_risk_profiling("HS#" VARCHAR, ProcessName VARCHAR, GowningStatus VARCHAR, SubprocessID VARCHAR, SubprocessName VARCHAR, ProductCondition VARCHAR, BarrierSystem VARCHAR, DecontaminationStatus VARCHAR, AllowedMovementSpeed VARCHAR, "Task#inSP" VARCHAR, TaskID VARCHAR, TaskName VARCHAR, ProductSterilizationStatus VARCHAR, DegreeOfVisibility VARCHAR, DistToObj VARCHAR, DegreeOfTactility VARCHAR, "Frame#inTask" VARCHAR, FrameID VARCHAR, FrameDescription VARCHAR, "HS#inFrame" VARCHAR, HazardScenario VARCHAR, NumberOfCriticalSurfaces VARCHAR, InteractionWithCritSurf VARCHAR, NumbActObj VARCHAR, WeightObj VARCHAR, SizeObj VARCHAR, HandlingOfObj VARCHAR, SpatialProximityToProduct VARCHAR, ExectionPace VARCHAR, BatchRecoverability VARCHAR, FrameSubject VARCHAR, FrameAction VARCHAR, FrameObject1 VARCHAR, FrameObject2 VARCHAR, FrameObject3 VARCHAR, FrameObject4 VARCHAR, AddIdentif VARCHAR, FrameLocation VARCHAR, FrameProgressTracker VARCHAR, HazardScenarioAction VARCHAR, HazardScenarioObject VARCHAR, HazardScenarioObjectInfo VARCHAR, HazardScenarioCQA1 VARCHAR, HazardCategory VARCHAR, HazardSpecification VARCHAR, H_Sev VARCHAR, RM_Sev VARCHAR, WH_Sev VARCHAR, H_Lik VARCHAR, RM_Lik VARCHAR, WH_Lik VARCHAR, WHC VARCHAR, LN VARCHAR, ProductConditionScr VARCHAR, "ProductSterilizationStatusScr
" VARCHAR, SpatialProximityToProductScore VARCHAR, NumberOfCriticalSurfacesScore VARCHAR, BatchRecoverabilityScr VARCHAR, DecontaminationStatusScr VARCHAR, BarrierSystemScr VARCHAR, GowningStatusScr VARCHAR, InteractionWithCritSurfScr VARCHAR, NumbActObjScr VARCHAR, DegreeOfVisibilityScr VARCHAR, DistToObjScr VARCHAR, DegreeOfTactilityScr VARCHAR, ErgonomicFreedomScr VARCHAR, HandlingOfObjScr VARCHAR, WeightObjScr VARCHAR, SizeObjScr VARCHAR, ComplexityScr VARCHAR, MovementSpeedScr VARCHAR, ExectionPaceScore VARCHAR, FrameProgressTrackerScr VARCHAR, maximum_complexity_object VARCHAR, _source VARCHAR);;
CREATE TABLE seed_asset(id VARCHAR, file_name VARCHAR, start_time INTEGER, stop_time INTEGER, created_by VARCHAR, created_on VARCHAR, modified_by VARCHAR, modified_on VARCHAR, description INTEGER, file_hash VARCHAR, note INTEGER, asset_group_id INTEGER, "type" VARCHAR, duration DOUBLE, file_size INTEGER, "extension" VARCHAR, process_id INTEGER, s3_key VARCHAR);;
CREATE TABLE seed_asset_process_link(file_name VARCHAR, "name" VARCHAR);;
CREATE TABLE seed_frame_factory_customer(id INTEGER, created_by VARCHAR, created_on VARCHAR, modified_by VARCHAR, modified_on VARCHAR, "name" VARCHAR, description INTEGER, code_name INTEGER);;
CREATE TABLE seed_frame_factory_hierarchy(customer VARCHAR, project VARCHAR, process VARCHAR, subprocess VARCHAR, task VARCHAR, frame VARCHAR, footage_timestamp FLOAT);;
CREATE TABLE seed_frame_factory_project(id INTEGER, created_by VARCHAR, created_on VARCHAR, modified_by VARCHAR, modified_on VARCHAR, project_status VARCHAR, "name" VARCHAR, site_id INTEGER, customer_id INTEGER, "type" VARCHAR, product_name VARCHAR, dosage_form INTEGER, target_concentration INTEGER, active_ingredient INTEGER, excipients INTEGER, sensitivity INTEGER, manufacturing_site VARCHAR, filling_line VARCHAR, target_volume INTEGER);;
CREATE TABLE stg_object(_source VARCHAR, base_obj VARCHAR, obj VARCHAR, weight VARCHAR, size VARCHAR, handling_difficulty VARCHAR, decontamination VARCHAR, sterilization VARCHAR, filter_integrity_testing VARCHAR, hepa_filter_integrity_testing VARCHAR, sterilization_in_place VARCHAR, cleaning_in_place VARCHAR, cleaning_procedures VARCHAR, equipment_cleaning_procedures VARCHAR, material_personnel_flow VARCHAR, surface_disinfection VARCHAR, zoning_concept VARCHAR, double_bagging VARCHAR, redundant_equipment VARCHAR, single_use_systems VARCHAR, contact_surface_plates VARCHAR, swabs VARCHAR);;
CREATE TABLE stg_risk_profiling(process_name VARCHAR, subprocess_name VARCHAR, subprocess_groupid VARCHAR, task_name VARCHAR, task_groupid VARCHAR, frame VARCHAR, frame_groupid VARCHAR, hazard VARCHAR, hazard_groupid VARCHAR, frame_subject VARCHAR, frame_action VARCHAR, direct_object VARCHAR, indirect_object VARCHAR, object_3 VARCHAR, object_4 VARCHAR, frame_progress_tracker VARCHAR, hazard_action VARCHAR, hazard_object VARCHAR, hazard_category VARCHAR, hazard_specification VARCHAR, gowning_status VARCHAR, product_condition VARCHAR, barrier_system VARCHAR, decontamination_status VARCHAR, allowed_movement_speed VARCHAR, product_sterilization VARCHAR, degree_of_visibility VARCHAR, distance_to_object VARCHAR, degree_of_tactility VARCHAR, number_of_critical_surfaces VARCHAR, interaction_with_critical_surfaces VARCHAR, number_of_active_objects VARCHAR, spatial_proximity_to_product VARCHAR, execution_pace VARCHAR, batch_recoverability VARCHAR, cqa VARCHAR, frame_location VARCHAR, H_Sev FLOAT, RM_Sev FLOAT, WH_Sev FLOAT, H_Lik FLOAT, RM_Lik FLOAT, WH_Lik FLOAT, WHC FLOAT, LN FLOAT, maximum_complexity_object VARCHAR, _source VARCHAR, project_id INTEGER, _insertion_order BIGINT);;

